# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soundable', '0003_auto_20191016_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='purchase',
            new_name='purchases',
        ),
    ]
