# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soundable', '0004_auto_20191016_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
